[project]
name = "api-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    alembic
    backports-datetime-fromisoformat
    bcrypt
    blinker
    cffi
    click
    Flask
    Flask-JWT-Extended
    Flask-Migrate
    Flask-SQLAlchemy
    greenlet
    itsdangerous
    Jinja2
    Mako
    MarkupSafe
    marshmallow
    marshmallow-sqlalchemy
    passlib
    pycparser
    PyJWT
    PyMySQL
    SQLAlchemy
    typing_extensions
    Werkzeug
]